In [17]:
#Importing Required Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

#Importing selenium webdriver
from selenium import webdriver

#Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException,ElementNotInteractableException,NoSuchElementException 

#Importing requests
import requests

#importing regex
import re

1. Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [18]:
# Activating the chrome browser
driver=webdriver.Chrome(r"C:/Users/tribe/Downloads/chromedriver_win32/chromedriver.exe")
#Loading url to the chrome driver
url = 'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(url)

<ipython-input-18-5aeb4211dafa>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/tribe/Downloads/chromedriver_win32/chromedriver.exe")

In [19]:
driver.maximize_window()

In [20]:
#creating list for rank, uploader)name, video name, no of views, date of upload
rank = []
video_names = []
artist = []
views = []
upload_dates = []

In [21]:
#getting ranks of the videos
try:
    rank_obj = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[1]')[:30]
    rank_obj
    for i in rank_obj:
        rank.append(i.text.replace('.',''))
except NoSuchElementException:
    rank.append('-')
print(rank)
print("++++++++++++++++++++++++++++++++++")
#getting names of the videos
try:
    videoname_obj = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[2]')[:30]
    videoname_obj
    for i in videoname_obj:
        video_names.append(i.text)
except NoSuchElementException:
    video_names.append('-')
print(video_names)
print("++++++++++++++++++++++++++++++++++")
#getting names of artist
try:
    uploader_obj = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[3]')[:30]
    for i in uploader_obj:
        artist.append(i.text)
except NoSuchElementException:
    artist.append('-')
print(artist)
print("++++++++++++++++++++++++++++++++++++++++")
#getting numbers of views of the videos
try:
    view_obj = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[4]')[:30]
    view_obj
    for i in view_obj:
        views.append(i.text)
except NoSuchElementException:
    views.append('-')
print(views)
print("++++++++++++++++++++++++++++++++++++++")
#getting upload date
try:
    date_obj = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[5]')[:30]
    date_obj
    for i in date_obj:
        upload_dates.append(i.text)
except NoSuchElementException:
    upload_dates.append('-')
print(upload_dates)
print("+++++++++++++++++++++++++++++++++++++++++")

<ipython-input-21-5c592bf0f1c9>:3: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  rank_obj = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[1]')[:30]

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30']
++++++++++++++++++++++++++++++++++

<ipython-input-21-5c592bf0f1c9>:13: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  videoname_obj = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[2]')[:30]

['"Baby Shark Dance"[3]', '"Despacito"[6]', '"Johny Johny Yes Papa"[12]', '"Shape of You"[13]', '"See You Again"[15]', '"Bath Song"[20]', '"Learning Colors – Colorful Eggs on a Farm"[21]', '"Masha and the Bear – Recipe for Disaster"[22]', '"Uptown Funk"[23]', '"Phonics Song with Two Words"[24]', '"Gangnam Style"[25]', '"Dame Tu Cosita"[30]', '"Sugar"[31]', '"Sorry"[32]', '"Roar"[33]', '"Wheels on the Bus"[34]', '"Counting Stars"[35]', '"Thinking Out Loud"[36]', '"Girls Like You"[37]', '"Faded"[38]', '"Dark Horse"[39]', '"Axel F"[40]', '"Let Her Go"[41]', '"Bailando"[42]', '"Lean On"[43]', '"Shake It Off"[44]', '"Baa Baa Black Sheep"[45]', '"Perfect"[46]', '"Waka Waka (This Time for Africa)"[47]', '"Mi Gente"[48]']
++++++++++++++++++++++++++++++++++

<ipython-input-21-5c592bf0f1c9>:23: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  uploader_obj = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[3]')[:30]

["Pinkfong Baby Shark - Kids' Songs & Stories", 'Luis Fonsi', 'LooLoo Kids', 'Ed Sheeran', 'Wiz Khalifa', 'Cocomelon – Nursery Rhymes', 'Miroshka TV', 'Get Movies', 'Mark Ronson', 'ChuChu TV', 'Psy', 'El Chombo', 'Maroon 5', 'Justin Bieber', 'Katy Perry', 'Cocomelon – Nursery Rhymes', 'OneRepublic', 'Ed Sheeran', 'Maroon 5', 'Alan Walker', 'Katy Perry', 'Crazy Frog', 'Passenger', 'Enrique Iglesias', 'Major Lazer', 'Taylor Swift', 'Cocomelon – Nursery Rhymes', 'Ed Sheeran', 'Shakira', 'J Balvin']
++++++++++++++++++++++++++++++++++++++++

<ipython-input-21-5c592bf0f1c9>:32: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  view_obj = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[4]')[:30]

['10.00', '7.70', '6.10', '5.58', '5.38', '4.86', '4.55', '4.48', '4.42', '4.41', '4.31', '3.80', '3.62', '3.50', '3.50', '3.50', '3.48', '3.39', '3.21', '3.21', '3.21', '3.17', '3.15', '3.15', '3.15', '3.13', '3.07', '3.06', '3.03', '3.03']
++++++++++++++++++++++++++++++++++++++

<ipython-input-21-5c592bf0f1c9>:42: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  date_obj = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[5]')[:30]

['June 17, 2016', 'January 12, 2017', 'October 8, 2016', 'January 30, 2017', 'April 6, 2015', 'May 2, 2018', 'February 27, 2018', 'January 31, 2012', 'November 19, 2014', 'March 6, 2014', 'July 15, 2012', 'April 5, 2018', 'January 14, 2015', 'October 22, 2015', 'September 5, 2013', 'May 24, 2018', 'May 31, 2013', 'October 7, 2014', 'May 31, 2018', 'December 3, 2015', 'February 20, 2014', 'June 16, 2009', 'July 25, 2012', 'April 11, 2014', 'March 22, 2015', 'August 18, 2014', 'June 25, 2018', 'November 9, 2017', 'June 4, 2010', 'June 29, 2017']
+++++++++++++++++++++++++++++++++++++++++

In [22]:
print(len(views),len(rank),len(video_names),len(artist),len(upload_dates))

30 30 30 30 30

In [23]:
#Since the length are same,we can creat dataframe
WIKI_VIEWS=pd.DataFrame({})
WIKI_VIEWS['RANK']=rank
WIKI_VIEWS['VIDEOS_NAME']=video_names
WIKI_VIEWS['ARTIST']=artist
WIKI_VIEWS['VIEWS']=views
WIKI_VIEWS['UPLOAD_DATE']=upload_dates
WIKI_VIEWS.reset_index(drop=True,inplace=True)
WIKI_VIEWS.index+=1
WIKI_VIEWS

,RANK,VIDEOS_NAME,ARTIST,VIEWS,UPLOAD_DATE
1,1,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,10.00,"June 17, 2016"
2,2,"""Despacito""[6]",Luis Fonsi,7.70,"January 12, 2017"
3,3,"""Johny Johny Yes Papa""[12]",LooLoo Kids,6.10,"October 8, 2016"
4,4,"""Shape of You""[13]",Ed Sheeran,5.58,"January 30, 2017"
5,5,"""See You Again""[15]",Wiz Khalifa,5.38,"April 6, 2015"
6,6,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,4.86,"May 2, 2018"
7,7,"""Learning Colors – Colorful Eggs on a Farm""[21]",Miroshka TV,4.55,"February 27, 2018"
8,8,"""Masha and the Bear – Recipe for Disaster""[22]",Get Movies,4.48,"January 31, 2012"
9,9,"""Uptown Funk""[23]",Mark Ronson,4.42,"November 19, 2014"
10,10,"""Phonics Song with Two Words""[24]",ChuChu TV,4.41,"March 6, 2014"
11,11,"""Gangnam Style""[25]",Psy,4.31,"July 15, 2012"
12,12,"""Dame Tu Cosita""[30]",El Chombo,3.80,"April 5, 2018"
13,13,"""Sugar""[31]",Maroon 5,3.62,"January 14, 2015"
14,14,"""Sorry""[32]",Justin Bieber,3.50,"October 22, 2015"
15,15,"""Roar""[33]",Katy Perry,3.50,"September 5, 2013"
16,16,"""Wheels on the Bus""[34]",Cocomelon – Nursery Rhymes,3.50,"May 24, 2018"
17,17,"""Counting Stars""[35]",OneRepublic,3.48,"May 31, 2013"
18,18,"""Thinking Out Loud""[36]",Ed Sheeran,3.39,"October 7, 2014"
19,19,"""Girls Like You""[37]",Maroon 5,3.21,"May 31, 2018"
20,20,"""Faded""[38]",Alan Walker,3.21,"December 3, 2015"
21,21,"""Dark Horse""[39]",Katy Perry,3.21,"February 20, 2014"
22,22,"""Axel F""[40]",Crazy Frog,3.17,"June 16, 2009"
23,23,"""Let Her Go""[41]",Passenger,3.15,"July 25, 2012"
24,24,"""Bailando""[42]",Enrique Iglesias,3.15,"April 11, 2014"
25,25,"""Lean On""[43]",Major Lazer,3.15,"March 22, 2015"
26,26,"""Shake It Off""[44]",Taylor Swift,3.13,"August 18, 2014"
27,27,"""Baa Baa Black Sheep""[45]",Cocomelon – Nursery Rhymes,3.07,"June 25, 2018"
28,28,"""Perfect""[46]",Ed Sheeran,3.06,"November 9, 2017"
29,29,"""Waka Waka (This Time for Africa)""[47]",Shakira,3.03,"June 4, 2010"
30,30,"""Mi Gente""[48]",J Balvin,3.03,"June 29, 2017"

Q2.Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [119]:
#Activating the Chrome brouser
driver=webdriver.Chrome(r"C:/Users/tribe/Downloads/chromedriver_win32/chromedriver.exe")

<ipython-input-119-9c4a422d5be7>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/tribe/Downloads/chromedriver_win32/chromedriver.exe")

In [120]:
driver.get(' https://www.bcci.tv/')

In [121]:
seachinternational=driver.find_element_by_xpath("//li[@class='nav-item ml-0']/a")
driver.get(seachinternational.get_attribute('href'))

<ipython-input-121-52e86f7a302c>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  seachinternational=driver.find_element_by_xpath("//li[@class='nav-item ml-0']/a")

In [122]:
try:
    format=driver.find_elements_by_xpath("//div[@class='cSBDisplay ng-binding']")
    format[1].click()
except:
    print("Error Occured")

<ipython-input-122-da181e310221>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  format=driver.find_elements_by_xpath("//div[@class='cSBDisplay ng-binding']")

In [123]:
formatODI=driver.find_elements_by_xpath("//div[@class='cSBListItems ng-scope']")
formatODI[1].click()

<ipython-input-123-0607d301c5ce>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  formatODI=driver.find_elements_by_xpath("//div[@class='cSBListItems ng-scope']")

In [124]:
matchest=driver.find_elements_by_xpath("//span[@class='ng-binding']")
matches=[]
matches.append([i.text for i in matchest])
matches

<ipython-input-124-12248c73a48d>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  matchest=driver.find_elements_by_xpath("//span[@class='ng-binding']")

[['ICC MENS UNDER 19 WORLD CUP 2022',
  'ICC MENS UNDER 19 WORLD CUP 2022',
  'INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22',
  'INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22',
  'ICC MENS UNDER 19 WORLD CUP 2022',
  'INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22',
  'WEST INDIES TOUR OF INDIA ODI SERIES 2022',
  'WEST INDIES TOUR OF INDIA ODI SERIES 2022']]

In [127]:
series=[]
series.extend([i.split(" ")[-1]for i in matches[0]])
series

['2022', '2022', '2021/22', '2021/22', '2022', '2021/22', '2022', '2022']

In [128]:
place=driver.find_elements_by_xpath("//div[@class='fix-place ng-binding ng-scope']")
venue=[]
venue.extend([i.text.split("-")[1] for i in place])
venue

<ipython-input-128-dbbb2e5649e5>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  place=driver.find_elements_by_xpath("//div[@class='fix-place ng-binding ng-scope']")

[' Providence Stadium, Guyana',
 ' Brian Lara Stadium, Trinidad',
 ' Boland Park, Paarl',
 ' Boland Park, Paarl',
 ' Brian Lara Stadium, Trinidad',
 ' Newlands, Cape Town',
 ' NARENDRA MODI STADIUM, Ahmedabad',
 ' Sawai Mansingh Stadium, Jaipur']

In [129]:
dateTag=driver.find_elements_by_xpath("//h5[@class='ng-binding']")
date=[]
date.extend([i.text for i in dateTag])
date

<ipython-input-129-32bada8d4bc5>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  dateTag=driver.find_elements_by_xpath("//h5[@class='ng-binding']")

['15 JAN 2022',
 '19 JAN 2022',
 '19 JAN 2022',
 '21 JAN 2022',
 '22 JAN 2022',
 '23 JAN 2022',
 '6 FEB 2022',
 '9 FEB 2022']

In [130]:
timeTag=driver.find_elements_by_xpath("//h5[@class='text-right ng-binding']")
time=[]
time.extend([i.text for i in timeTag])
time

<ipython-input-130-1a98216242c4>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  timeTag=driver.find_elements_by_xpath("//h5[@class='text-right ng-binding']")

['7:30 PM IST',
 '7:30 PM IST',
 '2:00 PM IST',
 '2:00 PM IST',
 '7:30 PM IST',
 '2:00 PM IST',
 '9:30 AM IST',
 '9:30 AM IST']

In [131]:
df=pd.DataFrame()

df['Matches']=matches[0]

df['Series']=series

df['Place']=venue

df['date']=date

df['Time']=time
df

,Matches,Series,Place,date,Time
0,ICC MENS UNDER 19 WORLD CUP 2022,2022,"Providence Stadium, Guyana",15 JAN 2022,7:30 PM IST
1,ICC MENS UNDER 19 WORLD CUP 2022,2022,"Brian Lara Stadium, Trinidad",19 JAN 2022,7:30 PM IST
2,INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,2021/22,"Boland Park, Paarl",19 JAN 2022,2:00 PM IST
3,INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,2021/22,"Boland Park, Paarl",21 JAN 2022,2:00 PM IST
4,ICC MENS UNDER 19 WORLD CUP 2022,2022,"Brian Lara Stadium, Trinidad",22 JAN 2022,7:30 PM IST
5,INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,2021/22,"Newlands, Cape Town",23 JAN 2022,2:00 PM IST
6,WEST INDIES TOUR OF INDIA ODI SERIES 2022,2022,"NARENDRA MODI STADIUM, Ahmedabad",6 FEB 2022,9:30 AM IST
7,WEST INDIES TOUR OF INDIA ODI SERIES 2022,2022,"Sawai Mansingh Stadium, Jaipur",9 FEB 2022,9:30 AM IST

In [132]:
driver.close()

Q3.Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
A) Name
B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [134]:
# Activating the chrome browser
driver=webdriver.Chrome(r"C:/Users/tribe/Downloads/chromedriver_win32/chromedriver.exe")
driver.get("https://www.guru99.com/")

<ipython-input-134-f6ca9ed7dc42>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/tribe/Downloads/chromedriver_win32/chromedriver.exe")

In [135]:
driver.find_elements_by_xpath("//span[@class='kadence-svg-iconset']")[0].click()

<ipython-input-135-bd1156f89445>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  driver.find_elements_by_xpath("//span[@class='kadence-svg-iconset']")[0].click()

In [136]:
try:
    close=driver.find_elements_by_xpath("//span[@class='kadence-svg-iconset']")
    close[10].click()
    searchBar=driver.find_element_by_xpath("//input[@class='gsc-input']")
    searchBar.send_keys("selenium exception")
except:
    searchBar=driver.find_element_by_xpath("//input[@class='gsc-input']")
    searchBar.send_keys("selenium exception")

<ipython-input-136-65a65d6686d2>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  close=driver.find_elements_by_xpath("//span[@class='kadence-svg-iconset']")
<ipython-input-136-65a65d6686d2>:4: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  searchBar=driver.find_element_by_xpath("//input[@class='gsc-input']")

In [137]:
clickButton=driver.find_element_by_xpath("//button[@class='gsc-search-button gsc-search-button-v2']")
clickButton.click()

<ipython-input-137-804654303c84>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  clickButton=driver.find_element_by_xpath("//button[@class='gsc-search-button gsc-search-button-v2']")

In [138]:
urls=[]
try:
    urlTag=driver.find_elements_by_xpath("//a[@class='gs-title']")
    urls.extend([i.get_attribute('href') for i in urlTag[:20:2]])
except:
    urls.append('-')

<ipython-input-138-db3f5c9f8b07>:3: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  urlTag=driver.find_elements_by_xpath("//a[@class='gs-title']")

In [140]:
Name=[]
desc=[]
try:
    for i in urls:
        driver.get(i)
        NameTag=driver.find_element_by_xpath("//h1[@class='entry-title']")
        Name.append(NameTag.text)
        descTag=driver.find_elements_by_xpath("//div/p")
        desc.extend([j.text for j in descTag[:2]])
except:
    Name.append("-")
    desc.append("-")
description=[]
for i in range(0,len(desc),2):
    description.append(desc[i]+desc[i+1])
df=pd.DataFrame()
df['Name']=Name
df['Description']=description

<ipython-input-140-3e845b33125c>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  NameTag=driver.find_element_by_xpath("//h1[@class='entry-title']")
<ipython-input-140-3e845b33125c>:8: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  descTag=driver.find_elements_by_xpath("//div/p")

In [141]:
df

,Name,Description
0,Selenium Exception Handling (Common Exceptions...,An exception is an error that happens at the t...
1,"Implicit, Explicit and Fluent Wait in Selenium...",
2,Selenium Alert & Popup Window Handling: How to...,
3,Top 100 Selenium Interview Questions and Answe...,
4,How to Handle SSL Certificate in Selenium WebD...,SSL (Secure Sockets Layer) is a standard secur...
5,Download Geckodriver: How to Install Using Fir...,The term Gecko stands for a Web Browser engine...
6,Selenium Tutorial for Beginners: Learn WebDriv...,Selenium is a popular open-source web-based au...
7,TestNG @Test Priority in Selenium,"TestNG is a Testing framework, that covers dif..."
8,How to Take Screenshot in Selenium WebDriver,A Screenshot in Selenium Webdriver is used for...
9,"Python Exception Handling: try, catch, finally...",An exception is an error which happens at the ...

Q4.Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP
D) GSDPbbbbbbbbb
E) Share
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [89]:
# Activating the chrome browser
driver=webdriver.Chrome(r"C:/Users/tribe/Downloads/chromedriver_win32/chromedriver.exe")

<ipython-input-89-42b730a61afd>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/tribe/Downloads/chromedriver_win32/chromedriver.exe")

In [90]:
# Opening the statisticstimes.com
url = "http://statisticstimes.com/"
driver.get(url)

In [91]:
#clicking on economy button
economy=driver.find_element_by_xpath("//div[@class='dropdown'][2]/div/a[3]")
try:
    economy.click()
except ElementNotInteractableException:
    driver.get(economy.get_attribute('href'))

#clicking on gdp of indian states
indian_states=driver.find_element_by_xpath("//ul[@style='list-style-type:none;margin-left:20px;']//li[1]/a")

try:
    indian_states.click()
except ElementNotInteractableException:
    driver.get(indian_states.get_attribute('href')) 

#scraping rank
rank=[]
try:
    ranks=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[1]")
    for i in ranks:
        rank.append(i.text)
except NoSuchElementException:                 #handling no such element exception
    rank.append('No details available')

#scraping States
State=[]
try:
    states=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[2]")
    for i in states:
        State.append(i.text)
except NoSuchElementException:                 #handling no such element exception
    State.append('No details available')


#scraping GSDP(19-20)
GSDP_20=[]
try:
    info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[3]")
    for i in info:
        GSDP_20.append(i.text)
except NoSuchElementException:           #handling no such element exception
    GSDP_20.append('No details available')   
    
#scraping GSDP(18-19)
GSDP_19=[]
try:
    info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[4]")
    for i in info:
        GSDP_19.append(i.text)
except NoSuchElementException:        #handling no such element exception
    GSDP_19.append('No details available')

#scraping share (18-19)
share=[]
try:
    info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[5]")
    for i in info:
        share.append(i.text)
except NoSuchElementException:          #handling no such element exception
    share.append('No details available')

#scraping GDP(billion$)
GDP_billion=[]
try:
    info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[6]")
    for i in info:
        GDP_billion.append(i.text)
except NoSuchElementException:            #handling no such element exception
    GDP_billion.append('No details available')


#creatng dataframe
df=pd.DataFrame({'Rank':rank,
                'State':State,
                'GSDP(19-20)':GSDP_20,
                'GSDP(18-19)':GSDP_19,
                'Share(18-19)':share,
                'GDP(Billion_$)':GDP_billion})
df

<ipython-input-91-fd7100f9f667>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  economy=driver.find_element_by_xpath("//div[@class='dropdown'][2]/div/a[3]")
<ipython-input-91-fd7100f9f667>:9: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  indian_states=driver.find_element_by_xpath("//ul[@style='list-style-type:none;margin-left:20px;']//li[1]/a")
<ipython-input-91-fd7100f9f667>:19: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  ranks=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[1]")
<ipython-input-91-fd7100f9f667>:28: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  states=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[2]")
<ipython-input-91-fd7100f9f667>:38: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[3]")
<ipython-input-91-fd7100f9f667>:47: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[4]")
<ipython-input-91-fd7100f9f667>:56: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[5]")
<ipython-input-91-fd7100f9f667>:65: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[6]")

,Rank,State,GSDP(19-20),GSDP(18-19),Share(18-19),GDP(Billion_$)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

Q5.Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used
Note: - From the home page you have to click on the trending option from Explore menu through code

In [142]:
# Activating the chrome browser
driver=webdriver.Chrome(r"C:/Users/tribe/Downloads/chromedriver_win32/chromedriver.exe")

<ipython-input-142-42b730a61afd>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/tribe/Downloads/chromedriver_win32/chromedriver.exe")

In [143]:
driver.get('https://github.com/')

In [145]:
try:
    driver.find_elements_by_xpath("//details[@class='HeaderMenu-details details-overlay details-reset width-full']")[1].click()
except:
    print("Error!!")

<ipython-input-145-64b8b0a303b0>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  driver.find_elements_by_xpath("//details[@class='HeaderMenu-details details-overlay details-reset width-full']")[1].click()

In [146]:
try:
    driver.get(driver.find_elements_by_xpath("//a[@class='lh-condensed-ultra d-block no-underline position-relative Link--secondary py-2']")[10].get_attribute('href'))
except:
    print("Error!!")

<ipython-input-146-035169f6420e>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  driver.get(driver.find_elements_by_xpath("//a[@class='lh-condensed-ultra d-block no-underline position-relative Link--secondary py-2']")[10].get_attribute('href'))

In [147]:
url=[]
try:
    urlTag=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")
    url.extend([i.get_attribute('href') for i in urlTag])
except:
    print("Error!!")

<ipython-input-147-536c9a03d306>:3: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  urlTag=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")

In [148]:
Repository_title=[]
Repository_description=[]
Contributors_count=[]
Language_used=[]
for i in url:
    driver.get(i)
    try:
        Repository_title.append(driver.find_element_by_xpath("//strong[@class='mr-2 flex-self-stretch']").text)
    except:
        Repository_title.append("-")
    try:
        Repository_description.append(driver.find_element_by_xpath("//div[@class='BorderGrid-cell']/p").text)
    except:
        Repository_description.append("-")
    try:
        Contributors_count.append(driver.find_elements_by_xpath("//h2[@class='h4 mb-3']/a/span")[-1].text)
    except:
        Contributors_count.append("-")
    try:
        Language_used.append(driver.find_element_by_xpath("//span[@class='color-fg-default text-bold mr-1']").text)
    except:
        Language_used.append("-")

<ipython-input-148-73321c6c022e>:8: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Repository_title.append(driver.find_element_by_xpath("//strong[@class='mr-2 flex-self-stretch']").text)
<ipython-input-148-73321c6c022e>:12: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Repository_description.append(driver.find_element_by_xpath("//div[@class='BorderGrid-cell']/p").text)
<ipython-input-148-73321c6c022e>:16: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Contributors_count.append(driver.find_elements_by_xpath("//h2[@class='h4 mb-3']/a/span")[-1].text)
<ipython-input-148-73321c6c022e>:20: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Language_used.append(driver.find_element_by_xpath("//span[@class='color-fg-default text-bold mr-1']").text)

In [149]:
df=pd.DataFrame()
df['Repository_title']=Repository_title
df['Repository_description']=Repository_description
df['Contributors_count']=Contributors_count
df['Language_used']=Language_used
df

,Repository_title,Repository_description,Contributors_count,Language_used
0,SpoofThatMail,Bash script to check if a domain or list of do...,2,Shell
1,windowjs,Window.js is an open-source Javascript runtime...,2,C++
2,astro,"Build fast websites, faster. 🚀🧑‍🚀✨",216,TypeScript
3,CS-Notes,📚 技术面试必备基础知识、Leetcode、计算机操作系统、计算机网络、系统设计,231,Java
4,superset,Apache Superset is a Data Visualization and Da...,711,TypeScript
5,applied-ml,📚 Papers & tech blogs by companies sharing the...,34,-
6,ar-cutpaste,Cut and paste your surroundings using AR,6,TypeScript
7,jdog202201,京东2022炸年兽,2,C#
8,DevSecOps,Ultimate DevSecOps library,13,-
9,ConvNeXt,Code release for ConvNeXt model,3,Python
10,plutus-apps,The Plutus application platform,110,Haskell
11,crater,Open Source Invoicing Solution for Individuals...,66,PHP
12,AspNetCore-Developer-Roadmap,Roadmap to becoming an ASP.NET Core developer ...,20,-
13,powershell-windows-toolbox,-,,-
14,Data_Science_Masters_Program_2021,-,,Jupyter Notebook
15,LeetCode-Py,⛽️「算法通关手册」，超详细的「算法与数据结构」基础讲解教程，「LeetCode」650+ ...,2,Python
16,ethereumbook,"Mastering Ethereum, by Andreas M. Antonopoulos...",232,JavaScript
17,annotated_latex_equations,"Examples of how to create colorful, annotated ...",3,TeX
18,leveldb,LevelDB is a fast key-value storage library wr...,57,C++
19,yolov5,YOLOv5 🚀 in PyTorch > ONNX > CoreML > TFLite,203,Python
20,plutus-pioneer-program,-,12,Haskell
21,Files,A modern file manager that pushes the boundari...,168,C#
22,omni,The all-in-one tool to supercharge your produc...,5,JavaScript
23,zju-icicles,浙江大学课程攻略共享计划,86,HTML
24,zinc,Zinc Search engine. A lightweight alternative ...,10,Vue

In [150]:
driver.close()

Q6.Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/ You have to find the following details: A) Song name B) Artist name C) Last week rank D) Peak rank E) Weeks on board Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [68]:
# Activating the chrome browser
driver=webdriver.Chrome(r"C:/Users/tribe/Downloads/chromedriver_win32/chromedriver.exe")

<ipython-input-68-42b730a61afd>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/tribe/Downloads/chromedriver_win32/chromedriver.exe")

In [69]:
driver.get('https://www.billboard.com/')

In [70]:
#Creating empty lists for storing the scrapped data
Song=[]
Artist=[]
Lastweek=[]
Peak=[]
Weeks_on_board=[]

#Scrapping the data having the song name
song=driver.find_elements_by_xpath("//span[@class='chart-element__information__song text--truncate color--primary']")
for i in song:
    Song.append(i.text)
    
#Scrapping the data having the artist name
artist=driver.find_elements_by_xpath("//span[@class='chart-element__information__artist text--truncate color--secondary']")
for i in artist:
    Artist.append(i.text)
    
#Scrapping the data having the last week rank
last_week=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']")
for i in last_week:
    if i.text is None:
        Lastweek.append('-')
    else:
        Lastweek.append(i.text)
        
#Scrapping the data having the peak rank
peak=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']")
for i in peak:
    if i.text is None:
        Peak.append('-')
    else:
        Peak.append(i.text)
        
#Scrapping the data having weeks on board data
weeks=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']")
for i in weeks:
    if i.text is None:
         Weeks_on_board.append('-')
    else:
        Weeks_on_board.append(i.text)

<ipython-input-70-35e647e40e12>:9: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  song=driver.find_elements_by_xpath("//span[@class='chart-element__information__song text--truncate color--primary']")
<ipython-input-70-35e647e40e12>:14: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  artist=driver.find_elements_by_xpath("//span[@class='chart-element__information__artist text--truncate color--secondary']")
<ipython-input-70-35e647e40e12>:19: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  last_week=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']")
<ipython-input-70-35e647e40e12>:27: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  peak=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']")
<ipython-input-70-35e647e40e12>:35: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  weeks=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']")

In [71]:
#Creating a dataframe for the scrapped data
billboard=pd.DataFrame({'Song':Song,'Artist':Artist,'Last week Rank':Lastweek,'Peak Rank':Peak,'Weeks on board':Weeks_on_board})
billboard

df

,Name,Data_type,Task,Attribute_type,No_of_instances,No_of_attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021

Q7.Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [151]:
# Activating the chrome browser
driver=webdriver.Chrome(r"C:/Users/tribe/Downloads/chromedriver_win32/chromedriver.exe")

<ipython-input-151-42b730a61afd>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/tribe/Downloads/chromedriver_win32/chromedriver.exe")

In [155]:
driver.get('https://www.naukri.com/data-science-jobs?src=gnbjobs_homepage_srch')

In [156]:
driver.get(driver.find_element_by_xpath("//a[@title='Search Recruiters']").get_attribute("href"))

<ipython-input-156-f11d44ec8f1d>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.get(driver.find_element_by_xpath("//a[@title='Search Recruiters']").get_attribute("href"))

In [157]:
driver.find_element_by_xpath("//input[@class='sugInp']").send_keys("Data Science")

<ipython-input-157-4a084d9295c3>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_xpath("//input[@class='sugInp']").send_keys("Data Science")

In [158]:
driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']").click()

<ipython-input-158-69cd9170e890>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']").click()

In [159]:
Name=[]
Designation=[]
Company=[]
Skills_hire=[]
Location=[]
try:
    nameTag=driver.find_elements_by_xpath("//span[@class='fl ellipsis']")
    Name.extend([i.text for i in nameTag])
except:
    Name.append("-")
try:
    desTag=driver.find_elements_by_xpath("//span[@class='ellipsis clr']")
    Designation.extend([i.text for i in desTag])
except:
    Designation.append("-")

try:
    comTag=driver.find_elements_by_xpath("//a[@class='ellipsis']")[1::2]
    Company.extend([i.text for i in comTag])
except:
    Company.append("-")
    
try:
    skill=driver.find_elements_by_xpath("//div[@class='hireSec highlightable']")
    Skills_hire.extend([i.text for i in skill])
except:
    Skills_hire.append("-")

try:
    locTag=driver.find_elements_by_xpath("//small[@class='ellipsis']")
    try:
        Location.extend([i.text for i in locTag])
    except:
        Location.append("-")
except:
    Location.append("-")

<ipython-input-159-5f26190b10b5>:7: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  nameTag=driver.find_elements_by_xpath("//span[@class='fl ellipsis']")
<ipython-input-159-5f26190b10b5>:12: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  desTag=driver.find_elements_by_xpath("//span[@class='ellipsis clr']")
<ipython-input-159-5f26190b10b5>:18: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  comTag=driver.find_elements_by_xpath("//a[@class='ellipsis']")[1::2]
<ipython-input-159-5f26190b10b5>:24: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  skill=driver.find_elements_by_xpath("//div[@class='hireSec highlightable']")
<ipython-input-159-5f26190b10b5>:30: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  locTag=driver.find_elements_by_xpath("//small[@class='ellipsis']")

In [164]:
df=pd.DataFrame()
df["name"]=Name
df['Designation']=Designation
df['Company']=Company
df['Skills_hireFor']=Skills_hire
df['Location']=Location
df

,name,Designation,Company,Skills_hireFor,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
11,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
12,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
15,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Chandigarh
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
17,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
18,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
24,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
27,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",-
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Delhi
30,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Hyderabad / Secunderabad
31,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
32,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
33,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
34,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",New Delhi
35,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Chennai
36,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Aligarh
37,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Salt Lake City
38,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Pune
39,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Bengaluru / Bangalore
40,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Mumbai
41,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Indore
42,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Bengaluru / Bangalore
43,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",MYSORE
44,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
45,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bengaluru / Bangalore
46,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Mumbai
47,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",-
48,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",Hyderabad / Secunderabad
49,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learn...",Bengaluru / Bangalore

In [163]:
Location.insert(46,'-')
Location.insert(28,'-')

In [165]:
driver.close()

Q8.Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [66]:
# Activating the chrome browser
driver=webdriver.Chrome(r"C:/Users/tribe/Downloads/chromedriver_win32/chromedriver.exe")

<ipython-input-66-42b730a61afd>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/tribe/Downloads/chromedriver_win32/chromedriver.exe")

In [67]:
# Opening the theguardian.com
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"
driver.get(url)

In [57]:
#scrapping book names
book_name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[2]")
    for i in names:
        book_name.append(i.text)
except NoSuchElementException:              #handling no such element exception
    book_name.append('No details available')

#scrapping author names
author_name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[3]")
    for i in names:
        author_name.append(i.text)
except NoSuchElementException:#handling no such element exception
    author_name.append('No details available')


#scrapping Sale
Sale=[]
try:
    sale=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[4]")
    for i in sale:
        Sale.append(i.text)
except NoSuchElementException:#handling no such element exception
    Sale.append('No details available')    

#scrapping publisher
publisher=[]
try:
    publishers=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")
    for i in publishers:
        publisher.append(i.text)
except NoSuchElementException:#handling no such element exception
    publisher.append('No details available')

#scrapping genre
genre=[]
try:
    genres=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[6]")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:#handling no such element exception
    genre.append('No details available')

#creating dataframe
df=pd.DataFrame({"Book_name":book_name,
                "Author_name":author_name,
                'Volume sold':Sale,
                'Publisher':publisher,
                'Genre':genre})
df

<ipython-input-57-5761f591b187>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[2]")
<ipython-input-57-5761f591b187>:13: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[3]")
<ipython-input-57-5761f591b187>:23: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  sale=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[4]")
<ipython-input-57-5761f591b187>:32: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  publishers=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")
<ipython-input-57-5761f591b187>:41: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  genres=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[6]")

,Book_name,Author_name,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

Q9.Scrape the details most watched tv series of all time from imdb.com. Url = https://www.imdb.com/list/ls095964455/ You have to find the following details: A) Name B) Year span C) Genre D) Run time E) Ratings F) Votes

In [58]:
# Activating the chrome browser
driver=webdriver.Chrome(r"C:/Users/tribe/Downloads/chromedriver_win32/chromedriver.exe")

<ipython-input-58-42b730a61afd>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/tribe/Downloads/chromedriver_win32/chromedriver.exe")

In [59]:
# Opening the imdb.com
url = "https://www.imdb.com/list/ls095964455"
driver.get(url)

In [60]:
# scraping name of webseries
name=[]
try:
    names=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
    for i in names:
        name.append(i.text)
except NosuchElementException:#handling no such element exception
    name.append('No details available')


# scraping year of release
years=[]
try:
    span=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")
    for i in span:
        years.append(i.text)
except NosuchElementException:#handling no such element exception
    years.append('No details available')


# scraping genre
genre=[]
try:
    genres=driver.find_elements_by_xpath("//span[@class='genre']")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:#handling no such element exception
    genre.append('No details available')


# scraping run_time
run_time=[]
try:
    info=driver.find_elements_by_xpath("//span[@class='runtime']")
    for i in info:
        run_time.append(i.text)
except NoSuchElementException:#handling no such element exception
    run_time.append('No details available')


# scraping rating
rating=[]
try:
    info=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]")
    for i in info:
        rating.append(i.text)
except NoSuchElementException:#handling no such element exception
    rating.append('No details available')

# scraping votes
votes=[]
try:
    info=driver.find_elements_by_xpath("//span[@name='nv']")
    for i in info:
        votes.append(i.text)
except NoSuchElementException:#handling no such element exception
    votes.append('No details available')


#creating dataframe
df=pd.DataFrame({"Name":name,
                "years":years,
                "Genre":genre,
                "Run_time":run_time,
                "Rating":rating,
                "Votes":votes})
df

<ipython-input-60-64f8bc2f0ca7>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  names=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
<ipython-input-60-64f8bc2f0ca7>:14: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  span=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")
<ipython-input-60-64f8bc2f0ca7>:24: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  genres=driver.find_elements_by_xpath("//span[@class='genre']")
<ipython-input-60-64f8bc2f0ca7>:34: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  info=driver.find_elements_by_xpath("//span[@class='runtime']")
<ipython-input-60-64f8bc2f0ca7>:44: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  info=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]")
<ipython-input-60-64f8bc2f0ca7>:53: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  info=driver.find_elements_by_xpath("//span[@name='nv']")

,Name,years,Genre,Run_time,Rating,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,930,901"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"951,671"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"922,287"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"276,348"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"236,594"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"47,189"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"57,981"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"183,063"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"38,343"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"218,058"

Q10.Details of Datasets from UCI machine learning repositories. Url = https://archive.ics.uci.edu/ You have to find the following details: A) Dataset name B) Data type C) Task D) Attribute type E) No of instances F) No of attribute G) Year Note: - from the home page you have to go to the ShowAllDataset page through code.

In [62]:
# Activating the chrome browser
driver=webdriver.Chrome(r"C:/Users/tribe/Downloads/chromedriver_win32/chromedriver.exe")

<ipython-input-62-42b730a61afd>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(r"C:/Users/tribe/Downloads/chromedriver_win32/chromedriver.exe")

In [63]:
# Opening the imdb.com
url = "https://archive.ics.uci.edu/"
driver.get(url)

In [65]:
#clicking show all datasets link
show=driver.find_element_by_xpath("//a[@href='datasets.php']")
show.click()


#scraping dataset names
name=[]
try:
    names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('No details available')

#scraping data type
data_type=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in info[1:]:
         data_type.append(i.text)
except NoSuchElementException:
    data_type.append("No information")


#scraping dataset names
default_task=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in info[1:]:
         default_task.append(i.text)
except NoSuchElementException:
    default_task.append("No information")


#scraping dataset names
attr_type=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in info[1:]:
         attr_type.append(i.text)
except NoSuchElementException:
    attr_type.append("No information")


#scraping dataset names
no_of_instances=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in info[1:]:
         no_of_instances.append(i.text)
except NoSuchElementException:
    no_of_instances.append("No information")


#scraping dataset names
no_of_attributes=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in info[1:]:
         no_of_attributes.append(i.text)
except NoSuchElementException:
    no_of_attributes.append("No information")


#scraping dataset names
year=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in info[1:]:
         year.append(i.text)
except NoSuchElementException:
    year.append("No information")

#creating dataframe
df=pd.DataFrame({'Name':name,
                'Data_type':data_type,
                'Task':default_task,
                'Attribute_type':attr_type,
                'No_of_instances':no_of_instances,
                'No_of_attributes':no_of_attributes,
                'Year':year})
df

<ipython-input-65-df5420f50a39>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  show=driver.find_element_by_xpath("//a[@href='datasets.php']")
<ipython-input-65-df5420f50a39>:9: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
<ipython-input-65-df5420f50a39>:18: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
<ipython-input-65-df5420f50a39>:28: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
<ipython-input-65-df5420f50a39>:38: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
<ipython-input-65-df5420f50a39>:48: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
<ipython-input-65-df5420f50a39>:58: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
<ipython-input-65-df5420f50a39>:68: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")

,Name,Data_type,Task,Attribute_type,No_of_instances,No_of_attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021